// todasLasCiudades.enum.ts
import { BarriosBuenosAiresEnum } from "./barriosBuenosAires.enum";
import { BarriosCABAEnum } from "./barriosCaba.enum";

export enum TodasLasCiudadesEnum {
  // CABA
  AGRONOMIA = "Agronomía",
  ALMAGRO = "Almagro",
  BALVANERA = "Balvanera",
  BARRACAS = "Barracas",
  BELGRANO = "Belgrano",
  BOEDO = "Boedo",
  CABALLITO = "Caballito",
  CHACARITA = "Chacarita",
  COGHLAN = "Coghlan",
  COLEGIALES = "Colegiales",
  CONSTITUCION = "Constitución",
  FLORES = "Flores",
  FLORESTA = "Floresta",
  LA_BOCA = "La Boca",
  LA_PATERNAL = "La Paternal",
  LINIERS = "Liniers",
  MATADEROS = "Mataderos",
  MONTE_CASTRO = "Monte Castro",
  MONSERRAT = "Monserrat",
  NUEVA_POMPEYA = "Nueva Pompeya",
  NUNEZ = "Núñez",
  PALERMO = "Palermo",
  PARQUE_AVELLANEDA = "Parque Avellaneda",
  PARQUE_CHACABUCO = "Parque Chacabuco",
  PARQUE_CHAS = "Parque Chas",
  PARQUE_PATRICIOS = "Parque Patricios",
  PUERTO_MADERO = "Puerto Madero",
  RECOLETA = "Recoleta",
  RETIRO = "Retiro",
  SAAVEDRA = "Saavedra",
  SAN_CRISTOBAL = "San Cristóbal",
  SAN_NICOLAS = "San Nicolás",
  SAN_TELMO = "San Telmo",
  VELEZ_SARSFIELD = "Vélez Sarsfield",
  VERSALLES = "Versalles",
  VILLA_CRESPO = "Villa Crespo",
  VILLA_DEL_PARQUE = "Villa del Parque",
  VILLA_DEVOTO = "Villa Devoto",
  VILLA_GENERAL_MITRE = "Villa General Mitre",
  VILLA_LUGANO = "Villa Lugano",
  VILLA_LURO = "Villa Luro",
  VILLA_ORTUZAR = "Villa Ortúzar",
  VILLA_PUEYRREDON = "Villa Pueyrredón",
  VILLA_REAL = "Villa Real",
  VILLA_RIPILLO = "Villa Riachuelo",
  VILLA_SANTA_RITA = "Villa Santa Rita",
  VILLA_SOLDATI = "Villa Soldati",
  VILLA_URQUIZA = "Villa Urquiza",

  // BUENOS AIRES
  ESCOBAR = "Escobar",
  PILAR = "Pilar",
  TIGRE = "Tigre",
  SAN_FERNANDO = "San Fernando",
  SAN_ISIDRO = "San Isidro",
  VICENTE_LOPEZ = "Vicente López",
  MALVINAS_ARGENTINAS = "Malvinas Argentinas",
  JOSE_C_PAZ = "José C. Paz",
  SAN_MIGUEL = "San Miguel",
  GENERAL_SAN_MARTIN = "General San Martín",
  LA_MATANZA = "La Matanza",
  TRES_DE_FEBRERO = "Tres de Febrero",
  HURLINGHAM = "Hurlingham",
  ITUZAINGO = "Ituzaingó",
  MORON = "Morón",
  MERLO = "Merlo",
  MORENO = "Moreno",
  GENERAL_RODRIGUEZ = "General Rodríguez",
  MARCOS_PAZ = "Marcos Paz",
  AVELLANEDA = "Avellaneda",
  LANUS = "Lanús",
  LOMAS_DE_ZAMORA = "Lomas de Zamora",
  ALMIRANTE_BROWN = "Almirante Brown",
  QUILMES = "Quilmes",
  BERAZATEGUI = "Berazategui",
  FLORENCIO_VARELA = "Florencio Varela",
  ESTEBAN_ECHEVERRIA = "Esteban Echeverría",
  EZEIZA = "Ezeiza",
  EZPELETA_BERISSO = "Berisso",
  ENSENADA = "Ensenada",
  LA_PLATA = "La Plata",
  SAN_VICENTE = "San Vicente",
  PRESIDENTE_PERON = "Presidente Perón",
  CANUELAS = "Cañuelas",
}